spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
arkesel.api-key=${ARKESEL_API_KEY}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
mnotify.api-key=${MNOTIFY_API_KEY}
mnotify.base-url=https://api.mnotify.com/api/sms/quick
mtn.momo.primary.key=${MTN_MOMO_PRIMARY_KEY}
api.user.key=${API_USER_KEY}
mtn.momo.api.key=${MTN_MOMO_API_KEY}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
email.frontend-url=https://catholic-church-official.vercel.app
sms.provider.api.url=https://api.mnotify.com/api/sms/quick
sms.provider.api.key=${MNOTIFY_API_KEY}
sms.provider.sender.id=${MNOTIFY_SENDER_ID}
app.cors.allowed-origins=https://*.vercel.app,http://localhost:3000
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0
