spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
jwt.secret=${JWT_SECRET}
arkesel.api-key=${ARKESEL_API_KEY}
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=465
spring.mail.username=${BREVO_USERNAME}
spring.mail.password=${BREVO_PASSWORD}
brevo.api.key=${BREVO_API_KEY}
mail.from=${MAIL_FROM}
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_SERVICE_KEY}
supabase.bucket.menu-items=${SUPABASE_MENU_BUCKET:menu-items}
supabase.bucket.receipts=${SUPABASE_RECEIPT_BUCKET:receipts}
mnotify.api-key=${MNOTIFY_API_KEY}
mnotify.base-url=https://api.mnotify.com/api/sms/quick
mtn.momo.primary.key=${MTN_MOMO_PRIMARY_KEY}
api.user.key=${API_USER_KEY}
mtn.momo.api.key=${MTN_MOMO_API_KEY}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
email.frontend-url=https://catholic-church-official.vercel.app
sms.provider.api.url=https://api.mnotify.com/api/sms/quick
sms.provider.api.key=${MNOTIFY_API_KEY}
sms.provider.sender.id=${MNOTIFY_SENDER_ID}
app.cors.allowed-origins=https://*.vercel.app,http://localhost:3000
spring.liquibase.enabled=true
spring.liquibase.change-log=db/changelog/db.changelog-master.yaml
spring.jpa.properties.hibernate.format_sql=true
paystack.secret-key=${PAYSTACK_SECRET_KEY}
paystack.public-key=${PAYSTACK_PUBLIC_KEY}
paystack.base-url=https://api.paystack.co
paystack.webhook-secret=${PAYSTACK_SECRET_KEY}
paystack.currency=GHS
paystack.callback-url=${PAYSTACK_CALLBACK_URL:http://localhost:3000/payment/callback}
google.client-id=${GOOGLE_CLIENT_ID}
#cloudinary.cloud-name=GrillBros
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_API_SECRET}


spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.data-source-properties.prepareThreshold=0
